//Task 1. Create a bank account
//Develop a banking system. To do that, first, create an object named “bankAccount”
//with the following fields:
//“bankAccountID”, which is autogenerated
//“accountNumber”
//“credentials”, which is an array with a username, password, and pin
//“balance”, which is an amount of money
//“createdAt”, which is a date

const bankAccount={
    "bankAccountID":"Juan Dela Cruz",
    "accountNumber":"999888777666",
    "credentials":[{"username":"JDC123"},{"password":"m@p4gMah@l"},{"pin":"9876"},],
    "balance":"1000",
    "createdAt":"October 12, 2022",
}
// Task 2. Create a user account
//Create an object which represents a user account and has the following fields:
//“bankAccount”, which is an object from task 1
//“debitCard”, which is a card number
//“firstName”
//“lastName”
//“birthDate”
//“validID”, which is an array with a type of ID passport or driver’s license and the ID number
//“address”
const userAccount={
    "bankAccount":[bankAccount],
    "debitCard":"3456123413583245",
    "firstName":"Juan",
    "lastName":"Dela Cruz",
    "birthDate":"March 1, 1990",
    "validID":[
        {"typeOfID":"Passport", "idNumber":"989787867675"},
        {"typeOfID":"Driver's License", "idNumber":"334345465657"},
    ],
    "address":"Sitio Mabango, Brgy. Masarap Mabuhay, Marikina City",
}
// Task 3. Add functionality to the system
//Outside the objects, create functions that enable interaction with a user’s bank account:
//“getBankAccountDetails”, which checks if the username and password
//are correct and shows the bank account details
//“withdrawMoney”, which checks if the username and password are correct and
//enables getting money from the bank account using the account number
//“depositMoney”, which allows putting money in the bank account using
//the account number
var username="JDC123";
    function inputUsername(username){
        if (username==="JDC123"){
            console.log("Your username is correct");
        }else if (username!=="JDC123"){
            console.log("Incorrect username")
        }
    }
var password="m@p4gMah@l";
    function inputPassword(password){
        if (password==="m@p4gMah@l"){
            console.log("Your password is correct");
            console.log("Please check your account details- "+bankAccountDetails);
        }else if (password!=="m@p4gMah@l"){
            console.log("Incorrect password")
        }
    }
var accountNumber="999888777666";
    function inputAccountNumber(accountNumber){
        if (accountNumber==="999888777666"){
            console.log("Your account number is correct");
            console.log("Your're able to withdraw your money with the amount of "+balance);
        }else if (accountNumber!=="999888777666"){
            console.log("Incorrect account number")
        }
    }
var accountNumber1="999888777666";
    function inputAccountNumber1(accountNumber1){
        if (accountNumber1==="999888777666"){
            console.log("Your account number is correct");
            console.log("Your're able to deposit money with the amount of "+100);
        }else if (accountNumber1!=="999888777666"){
            console.log("Incorrect account number")
        }
    }
const balance=1000;
const bankAccountDetails="BankAccountID: Juan Dela Cruz, AccountNumber: 999888777666, Balance: 1000, CreatedAt: October 12, 2022";
function getBankAccountDetails(username,password){
}
function withdrawMoney(username,password,accountNumber){
}
function depositMoney(inputAccountNumber1){
    
}
getBankAccountDetails(inputUsername("1"),inputPassword("1"))
withdrawMoney(inputUsername("1"),inputPassword("1"),inputAccountNumber("1"))
depositMoney(inputAccountNumber1("1"))